# Generated by Django 2.0.2 on 2018-03-01 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('correct', models.BooleanField()),
                ('machine', models.BooleanField()),
                ('guess', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('photo_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Landmark'),
        ),
    ]
