# Generated by Django 2.0.2 on 2018-03-02 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='photo_url',
            new_name='photo',
        ),
    ]
