# Generated by Django 2.0.2 on 2018-03-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180301_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='wiki_sum',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='landmark',
            name='wiki_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='choice',
            name='guess',
            field=models.BooleanField(default=False),
        ),
    ]
