# Generated by Django 2.0.2 on 2018-03-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20180307_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='photo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
